name: libsemigroups-pybind11-doc

channels:
  - conda-forge

dependencies:
  - libsemigroups==2.0.0
  - pip
  - sphinx-copybutton==0.3.1
  - sphinxcontrib-bibtex==2.2.0
  - packaging
  - pip:
    - packaging
