name: Run standard tests
on: [pull_request]

jobs:
  py36:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Install libsemigroups_pybind11
        run: |
          python -m pip install .
      - name: Run tests
        run: make tests 
